/* Copyright 2019-2021 NXP
 * 
 * This software is owned or controlled by NXP and may only be used
 * strictly in accordance with the applicable license terms.  By expressly
 * accepting such terms or by downloading, installing, activating and/or
 * otherwise using the software, you are agreeing that you have read, and
 * that you agree to comply with and are bound by, such license terms.  If
 * you do not agree to be bound by the applicable license terms, then you
 * may not retain, install, activate or otherwise use the software.
 * 
 */

#ifndef UWBIOTVER_STR_VERSION_INFO_H_INCLUDED
#define UWBIOTVER_STR_VERSION_INFO_H_INCLUDED

/* clang-format off */
#define UWBIOTVER_STR_PROD_NAME          "UWBIOT"
#define UWBIOTVER_STR_VER_STRING_NUM     "v02.00.00"
#define UWBIOTVER_STR_PROD_NAME_VER_FULL "UWBIOT_v02.00.00"
#define UWBIOTVER_STR_VER_MAJOR          (2u)
#define UWBIOTVER_STR_VER_MINOR          (0u)
#define UWBIOTVER_STR_VER_DEV            (0u)

/* v02.00 = 20000u */
#define UWBIOTVER_STR_VER_MAJOR_MINOR ( 0 \
    | (UWBIOTVER_STR_VER_MAJOR * 10000u)    \
    | (UWBIOTVER_STR_VER_MINOR))

/* v02.00.00 = 200000000ULL */
#define UWBIOTVER_STR_VER_MAJOR_MINOR_DEV ( 0 \
    | (UWBIOTVER_STR_VER_MAJOR * 10000*10000u)    \
    | (UWBIOTVER_STR_VER_MINOR * 10000u)    \
    | (UWBIOTVER_STR_VER_DEV))

/* clang-format on */

/* Version Information:
 * Generated by:
 *     version_info.py (v2019.01.17_00)
 * 
 * Do not edit this file. Update:
 *     ../version_info.txt instead.
 * 
 * # Product
 * prod_name = "UWBIOT"
 * prod_desc = "UWBIOT"
 * 
 * # Programming language specific customizations
 * lang_c_prefix = "UWBIOTVER_STR"
 * lang_namespace = "nxp::UwbIoT"
 * 
 * # Version
 * v_major = "02"
 * v_minor = "00"
 * v_dev   = "00"
 * v_meta  = "" # Meta string identifier
 * 
 * # Maturity of library.  Alpha, Beta, Production
 * maturity = "A"
 * 
 * 
 * #
 * # MW v02.00.00 / SR040 FW v00.08.04
 * #    - Make a 02.00.00 version
 * #
 * # MW v01.09.05 / SR040 FW v00.08.04
 * #    - Copyright year updated to 2021
 * #
 * # MW v01.09.04 / SR040 FW v00.08.04
 * #    - Updated SP1 RAW TX
 * #
 * # MW v01.09.02 / SR040 FW v00.08.02
 * #    - FIX Max Num retry. Earlier, after 0xFFFF blocks, session
 * #      self terminated.
 * #
 * # MW v01.09.01 / SR040 FW v00.08.01
 * #    - TDoA + Tracker
 * #    - Updates on Boot handling
 * #    - Added new/more UCI Commands
 * #
 * # MW v01.09.00 / SR040 FW v00.08.00
 * #    - TDoA + Tracker
 * #
 * # MW v01.07.00 / SR040 FW v00.07.00(CQS)
 * #    - Mainline Develop
 * #
 * # MW v01.06.04 / SR040 FW v00.07.00
 * #    - Ongoing updates
 * #
 * # MW v01.06.05 / SR040 FW v00.07.00
 * #    - Logging update
 * #
 * # MW v01.06.04 / SR040 FW v00.07.00(CQS)
 * #    - Intermdiate release.
 * #
 * # MW v01.06.03 / SR040 FW v00.07.00
 * #    - Fixes for SPI and demo updates
 * #
 * # MW v01.06.02 / SR040 FW v00.07.00(CQS)
 * #    - Cleaner SPI Fixes for Test Mode
 * #    - Test mode updates
 * #
 * # MW v01.06.01 / SR040 FW v00.07.00(CQS)
 * #    - DEMO Fixes for Test Mode
 * #
 * # MW v01.06.00 / SR040 FW v00.07.00(CQS)
 * #    - CQS
 * #
 * # MW v01.05.00 / SR040 FW v00.06.00
 * #    - Updated radio configs
 * #
 * # MW v01.04.01 / SR040 FW v00.05.05
 * #    - HPRF Fixes
 * #
 */

#endif /* UWBIOTVER_STR_VERSION_INFO_H_INCLUDED */
